<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="models.dao.Sql2oUsersDaoTest" time="76.762" tests="16" errors="16" skipped="0" failures="0">
  <properties>
    <property name="idea.version" value="2020.3.3"/>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.282-b08"/>
    <property name="java.vm.vendor" value="Private Build"/>
    <property name="maven.multiModuleProjectDirectory" value="/home/michael/IdeaProjects/organisationalApi"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/home/michael/IdeaProjects/organisationalApi"/>
    <property name="intellij.debug.agent" value="true"/>
    <property name="java.runtime.version" value="1.8.0_282-8u282-b08-0ubuntu1~20.04-b08"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="maven.ext.class.path" value="/home/michael/idea/plugins/maven/lib/maven-event-listener.jar"/>
    <property name="classworlds.conf" value="/home/michael/idea/plugins/maven/lib/maven3/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib"/>
    <property name="jboss.modules.system.pkgs" value="com.intellij.rt"/>
    <property name="maven.conf" value="/home/michael/idea/plugins/maven/lib/maven3/conf"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="5.4.0-67-generic"/>
    <property name="user.home" value="/home/michael"/>
    <property name="user.timezone" value="Africa/Nairobi"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="user.name" value="michael"/>
    <property name="java.class.path" value="/home/michael/idea/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar:/home/michael/idea/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/home/michael/idea/lib/idea_rt.jar:/home/michael/idea/plugins/Groovy/lib/agent/gragent.jar:/home/michael/idea/plugins/java/lib/rt/debugger-agent.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-openjdk-amd64/jre"/>
    <property name="sun.java.command" value="org.codehaus.classworlds.Launcher -Didea.version=2020.3.3 heroku:deploy-war"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_282"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes"/>
    <property name="java.vendor" value="Private Build"/>
    <property name="maven.home" value="/home/michael/idea/plugins/maven/lib/maven3"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="instantiatesCorrectly" classname="models.dao.Sql2oUsersDaoTest" time="8.523">
    <error message="Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from &apos;classpath:db/create.sql&apos;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
</error>
    <system-out><![CDATA[clearing database
]]></system-out>
  </testcase>
  <testcase name="instantiatesCorrectly" classname="models.dao.Sql2oUsersDaoTest" time="8.524">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at models.dao.Sql2oUsersDaoTest.tearDown(Sql2oUsersDaoTest.java:35)
</error>
  </testcase>
  <testcase name="clearAll_clearsAllInstancesFromTheDatabaseCorrectly_true" classname="models.dao.Sql2oUsersDaoTest" time="9.082">
    <error message="Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from &apos;classpath:db/create.sql&apos;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
</error>
    <system-out><![CDATA[clearing database
]]></system-out>
  </testcase>
  <testcase name="clearAll_clearsAllInstancesFromTheDatabaseCorrectly_true" classname="models.dao.Sql2oUsersDaoTest" time="9.082">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at models.dao.Sql2oUsersDaoTest.tearDown(Sql2oUsersDaoTest.java:35)
</error>
  </testcase>
  <testcase name="findByIdReturnsCorrectInstanceOfClass" classname="models.dao.Sql2oUsersDaoTest" time="9.173">
    <error message="Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from &apos;classpath:db/create.sql&apos;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
</error>
    <system-out><![CDATA[clearing database
]]></system-out>
  </testcase>
  <testcase name="findByIdReturnsCorrectInstanceOfClass" classname="models.dao.Sql2oUsersDaoTest" time="9.173">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at models.dao.Sql2oUsersDaoTest.tearDown(Sql2oUsersDaoTest.java:35)
</error>
  </testcase>
  <testcase name="updatesCorrectlyUpdatesAllFieldsCorrectly" classname="models.dao.Sql2oUsersDaoTest" time="8.867">
    <error message="Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from &apos;classpath:db/create.sql&apos;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
</error>
    <system-out><![CDATA[clearing database
]]></system-out>
  </testcase>
  <testcase name="updatesCorrectlyUpdatesAllFieldsCorrectly" classname="models.dao.Sql2oUsersDaoTest" time="8.868">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at models.dao.Sql2oUsersDaoTest.tearDown(Sql2oUsersDaoTest.java:35)
</error>
  </testcase>
  <testcase name="deletesUserByIdCorrectly" classname="models.dao.Sql2oUsersDaoTest" time="16.448">
    <error message="Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from &apos;classpath:db/create.sql&apos;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
</error>
    <system-out><![CDATA[clearing database
]]></system-out>
  </testcase>
  <testcase name="deletesUserByIdCorrectly" classname="models.dao.Sql2oUsersDaoTest" time="16.448">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at models.dao.Sql2oUsersDaoTest.tearDown(Sql2oUsersDaoTest.java:35)
</error>
  </testcase>
  <testcase name="returnsCorrectSizeAfterInstantiation" classname="models.dao.Sql2oUsersDaoTest" time="7.79">
    <error message="Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from &apos;classpath:db/create.sql&apos;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
</error>
    <system-out><![CDATA[clearing database
]]></system-out>
  </testcase>
  <testcase name="returnsCorrectSizeAfterInstantiation" classname="models.dao.Sql2oUsersDaoTest" time="7.79">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at models.dao.Sql2oUsersDaoTest.tearDown(Sql2oUsersDaoTest.java:35)
</error>
  </testcase>
  <testcase name="returnsTheRightId" classname="models.dao.Sql2oUsersDaoTest" time="7.954">
    <error message="Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from &apos;classpath:db/create.sql&apos;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
</error>
    <system-out><![CDATA[clearing database
]]></system-out>
  </testcase>
  <testcase name="returnsTheRightId" classname="models.dao.Sql2oUsersDaoTest" time="7.954">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at models.dao.Sql2oUsersDaoTest.tearDown(Sql2oUsersDaoTest.java:35)
</error>
  </testcase>
  <testcase name="returnNothingWhenThereIsNoInstance" classname="models.dao.Sql2oUsersDaoTest" time="8.921">
    <error message="Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from &apos;classpath:db/create.sql&apos;" type="org.sql2o.Sql2oException">org.sql2o.Sql2oException: Could not acquire a connection from DataSource - No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:h2:mem:testing;INIT=RUNSCRIPT from 'classpath:db/create.sql'
	at models.dao.Sql2oUsersDaoTest.setUp(Sql2oUsersDaoTest.java:26)
</error>
    <system-out><![CDATA[clearing database
]]></system-out>
  </testcase>
  <testcase name="returnNothingWhenThereIsNoInstance" classname="models.dao.Sql2oUsersDaoTest" time="8.922">
    <error type="java.lang.NullPointerException">java.lang.NullPointerException
	at models.dao.Sql2oUsersDaoTest.tearDown(Sql2oUsersDaoTest.java:35)
</error>
  </testcase>
</testsuite>